---
# Source: demo-cicd/charts/productpage/templates/service-account.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: demo-cicd-productpage-sa-deployable
  namespace: demo-cicd-source
  labels:
    appname: demo-cicd-demo
    release: demo-cicd-demo
    component: productpage
    prereq: "yes"
spec:
  template:
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: demo-cicd-productpage
---
# Source: demo-cicd/charts/productpage/templates/clusterrole.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: demo-cicd-productpage-rbac-deployable
  namespace: demo-cicd-source
  labels:
    appname: demo-cicd-demo
    release: demo-cicd-demo
    component: productpage
    prereq: "yes"
spec:
  template:
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: productpage-lwdc-query
    rules:
    - apiGroups:
      - ""
      - apps
      resources:
      - clusters
      - nodes
      - services
      - configmaps
      - pods
      - endpoints
      - deployments
      verbs:
      - list
      - get
---
# Source: demo-cicd/charts/productpage/templates/rolebinding.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: demo-cicd-productpage-crb-deployable
  namespace: demo-cicd-source
  labels:
    appname: demo-cicd-demo
    release: demo-cicd-demo
    component: productpage
    prereq: "yes"
spec:
  template:
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: productpage-lwdc-rolebinding
      namespace: demo-cicd
    subjects:
    - kind: User
      name: system:serviceaccount:demo-cicd:demo-cicd-productpage
      apiGroup: rbac.authorization.k8s.io
    roleRef:
      kind: ClusterRole
      name: productpage-lwdc-query
      apiGroup: rbac.authorization.k8s.io
---
# Source: demo-cicd/charts/productpage/templates/service.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: demo-cicd-productpage-svc-deployable
  namespace: demo-cicd-source
  labels:
    appname: demo-cicd-demo
    release: demo-cicd-demo
    component: productpage
    prereq: "no"
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: productpage
      labels:
        app.kubernetes.io/name: productpage
        app.kubernetes.io/instance: demo-cicd-demo
    spec:
      ports:
        - port: 9080
          targetPort: http
          protocol: TCP
          name: http
      selector:
        app.kubernetes.io/name: productpage
        app.kubernetes.io/instance: demo-cicd-demo
---
---
# Source: demo-cicd/charts/productpage/templates/deployment.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: demo-cicd-productpage-deploy-deployable
  namespace: demo-cicd-source
  labels:
    appname: demo-cicd-demo
    release: demo-cicd-demo
    component: productpage
    prereq: "no"
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: demo-cicd-demo-productpage
      labels:
        app.kubernetes.io/name: productpage
        app.kubernetes.io/instance: demo-cicd-demo
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: productpage
          app.kubernetes.io/instance: demo-cicd-demo
      template:
        metadata:
          labels:
            app.kubernetes.io/name: productpage
            app.kubernetes.io/instance: demo-cicd-demo
        spec:
          serviceAccountName: demo-cicd-productpage
          containers:
            - env:
              - name: OPENTRACING_ENABLED
                value: "true"
              - name: JAEGER_SAMPLER_TYPE
                value: "probabilistic"
              - name: JAEGER_SAMPLER_PARAM
                value: "1"
              - name: LATENCY_SAMPLER_PARAM
                value: "1"
              name: productpage
              image: "docker.io/dymaczew/examples-demo-cicd-productpage-v1:2020.1.0.1"
              imagePullPolicy: IfNotPresent
              ports:
                - name: http
                  containerPort: 9080
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /health
                  port: http
              readinessProbe:
                httpGet:
                  path: /health
                  port: http
              volumeMounts:
              - mountPath: /opt/ibm/apm/serverconfig
                name: global-environment
              resources:
                {}               
          volumes:
          - name: global-environment
            secret:
              defaultMode: 420
              optional: true
              secretName: icam-server-secret
---
# Source: demo-cicd/templates/ingress.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: demo-cicd-ingress-deployable
  namespace: demo-cicd-source
  labels:
    appname: demo-cicd-demo
    release: demo-cicd-demo
    component: productpage
    prereq: "yes"
spec:
  template:
    apiVersion: networking.k8s.io/v1beta1
    kind: Ingress
    metadata:
      name: demo-cicd-ingress
      labels:
        app.kubernetes.io/name: productpage
        app.kubernetes.io/instance: demo-cicd-demo
    spec:
      rules:
        - http:
            paths:
              - path: /
                backend:
                  serviceName: productpage
                  servicePort: 9080
---
# Source: demo-cicd/templates/ingress.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: demo-cicd-route-deployable
  namespace: demo-cicd-source
  labels:
    appname: demo-cicd-demo
    release: demo-cicd-demo
    component: productpage
    prereq: "yes"
spec:
  template:
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: demo-cicd
      namespace: demo-cicd
    spec:
      to:
        kind: Service
        name: productpage
        weight: 100
      port:
        targetPort: http
      wildcardPolicy: None