# Source: demo-cicd/charts/mysqldb/templates/secret.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: demo-cicd-mysqldb-secret-deployable
  namespace: demo-cicd-source
  labels:
    appname: demo-cicd-demo
    release: demo-cicd-demo
    component: mysqldb
    prereq: "no"
spec:
  template:
    apiVersion: v1
    kind: Secret
    metadata:
      name: mysql-credentials
      namespace: demo-cicd
    type: Opaque
    data:
      rootpasswd: cGFzc3dvcmQ=
---
# Source: demo-cicd/charts/mysqldb/templates/service.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: demo-cicd-mysqldb-svc-deployable
  namespace: demo-cicd-source
  labels:
    appname: demo-cicd-demo
    release: demo-cicd-demo
    component: mysqldb
    prereq: "no"
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: mysqldb
      labels:
        app.kubernetes.io/name: mysqldb
        app.kubernetes.io/instance: demo-cicd-demo
    spec:
      ports:
        - port: 3306
          protocol: TCP
          name: tcp
      selector:
        app.kubernetes.io/name: mysqldb
        app.kubernetes.io/instance: demo-cicd-demo

---
# Source: demo-cicd/charts/mysqldb/templates/deployment.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: demo-cicd-mysqldb-deploy-deployable
  namespace: demo-cicd-source
  labels:
    appname: demo-cicd-demo
    release: demo-cicd-demo
    component: mysqldb
    prereq: "no"
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: demo-cicd-demo-mysqldb
      labels:
        app.kubernetes.io/name: mysqldb
        app.kubernetes.io/instance: demo-cicd-demo
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: mysqldb
          app.kubernetes.io/instance: demo-cicd-demo
      template:
        metadata:
          labels:
            app.kubernetes.io/name: mysqldb
            app.kubernetes.io/instance: demo-cicd-demo
        spec:
          containers:
            - name: mysqldb
              image: "docker.io/dymaczew/examples-demo-cicd-mysqldb:latest"
              imagePullPolicy: Always
              ports:
                - name: http
                  containerPort: 3306
                  protocol: TCP
              resources:
                {}                
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-credentials
                      key: rootpasswd

---
